from __future__ import annotations
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import typer
from rich.console import Console
from rich.markdown import Markdown
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn, BarColumn
from rich.syntax import Syntax
from rich.table import Table
from rich import box

from ctxkit.config.loader import load_config, DEFAULT_CONFIG_PATH
from ctxkit.config.models import CtxKitConfig

# ── ctxkit init ───────────────────────────────────────────────────────────────

def _detect_ollama_models() -> list[str]:
    """Return list of pulled Ollama model tags, or [] if Ollama is unavailable."""
    try:
        result = subprocess.run(
            ["ollama", "list"],
            capture_output=True, text=True, timeout=5,
        )
        if result.returncode != 0:
            return []
        models = []
        for line in result.stdout.splitlines()[1:]:  # skip header
            tag = line.split()[0] if line.split() else ""
            if tag:
                models.append(tag)
        return models
    except Exception:
        return []


def _is_apple_silicon() -> bool:
    import platform
    return platform.system() == "Darwin" and platform.machine() == "arm64"


def _detect_ram_gb() -> int:
    """Best-effort RAM detection. Returns 0 if unavailable."""
    try:
        import platform
        if platform.system() == "Darwin":
            result = subprocess.run(
                ["sysctl", "-n", "hw.memsize"], capture_output=True, text=True, timeout=3
            )
            return int(result.stdout.strip()) // (1024 ** 3)
        elif platform.system() == "Linux":
            import os
            page = os.sysconf("SC_PAGE_SIZE")
            pages = os.sysconf("SC_PHYS_PAGES")
            return (page * pages) // (1024 ** 3)
    except Exception:
        pass
    return 0


def _hardware_label() -> str:
    import platform
    ram = _detect_ram_gb()
    ram_str = f"{ram}GB RAM" if ram else "unknown RAM"
    if _is_apple_silicon():
        return f"Apple Silicon · {ram_str}"
    return f"{platform.machine()} · {ram_str}"


# Model suggestion tables — pure hardcoded priority lists.
# No LLM call, no network call. Logic:
#   1. If user already has a preferred model pulled → suggest that.
#   2. Otherwise suggest based on detected RAM tier.
#   3. Fall back to qwen3.5:4b if nothing matches.
# RAM tiers: <8GB = small, 8-16GB = mid, >16GB = large.

_PRIMARY_MODELS_SMALL = ["phi4-mini", "qwen3.5:4b", "llama3.2:3b"]
_PRIMARY_MODELS_MID   = ["qwen3.5:4b", "qwen3:8b", "phi4-mini"]
_PRIMARY_MODELS_LARGE = ["qwen3:8b", "qwen3.5:4b", "llama3.1:8b"]


def _suggest_primary_model(pulled: list[str], ram_gb: int = 0) -> str:
    if ram_gb >= 24:
        preferred = _PRIMARY_MODELS_LARGE
    elif ram_gb >= 8:
        preferred = _PRIMARY_MODELS_MID
    else:
        preferred = _PRIMARY_MODELS_SMALL
    for m in preferred:
        if any(p.startswith(m.split(":")[0]) for p in pulled):
            return m
    # nothing pulled — suggest first in tier as the thing to pull
    return preferred[0]


def _suggest_synth_model(pulled: list[str]) -> str:
    # phi4-mini is always right here — non-thinking, fast, reliable
    # suggest regardless of whether it's pulled so user knows what to pull
    return "phi4-mini"


def _suggest_embed_model(pulled: list[str], ram_gb: int = 0) -> str:
    # bge-m3 is higher quality but heavier (~1.2GB vs ~0.5GB)
    # only suggest on machines with enough headroom
    if ram_gb >= 16 and not _is_apple_silicon():
        if any(p.startswith("bge-m3") for p in pulled):
            return "bge-m3"
    return "nomic-embed-text"


def _write_init_config(
    vault_path: str,
    owner_name: str,
    backend: str,
    primary_model: str,
    synth_model: str,
    embed_backend: str,
    embed_model: str,
    api_key: str,
    out_path: Path,
) -> None:
    synth_line = f"  synthesise_model: {synth_model}" if backend == "ollama" and synth_model else "  # synthesise_model: phi4-mini  # uncomment + ollama pull phi4-mini"
    api_key_line = f"  api_key: {api_key}" if api_key else "  api_key: null"
    owner_line = f'  owner_name: "{owner_name}"' if owner_name else '  owner_name: ""  # set to your first name if vault has subfolders for other people'
    embed_model_field = "local_model" if embed_backend == "ollama" else "api_model"

    config_text = f"""# ctxkit config — generated by ctxkit init
# Edit any value, then run: ctxkit config --validate

vault:
  path: {vault_path}
{owner_line}
  excluded_folders:
    - noise
  excluded_extensions:
    - .canvas
    - .pdf

indexer:
  min_word_count: 50
  chunk_size: 512
  chunk_overlap: 64
  heading_aware_splitting: true
  preserve_tables: true
  preserve_code_blocks: true

embeddings:
  backend: {embed_backend}
  {embed_model_field}: {embed_model}

vector_store:
  persist_path: ~/.ctxkit/chroma_db
  collection_name: ctxkit_vault

retriever:
  keyword_prefilter: true
  top_k: 15
  similarity_threshold: 0.65
  context_block_max_words: 1000

ingester:
  similarity_threshold_high: 0.82
  similarity_threshold_low: 0.65
  conflict_detection: true

writer:
  append_position: end
  backup:
    enabled: true

llm:
  backend: {backend}
  model: {primary_model}
{synth_line}
{api_key_line}
  temperature: 0.2
  think: false
  max_tokens: 1000
  timeout_seconds: 30

manifest:
  drift_warning_threshold: 3

cli:
  theme: dark
  confirm_before_index: true

logging:
  log_level: INFO
"""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(config_text, encoding="utf-8")


_VERSION = "1.2.0"

app = typer.Typer(
    name="ctxkit",
    help="Context Portability and Knowledge Ingestion Tool",
    add_completion=False,
)
console = Console()
err_console = Console(stderr=True, style="bold red")

_cfg_option = typer.Option(None, "--config", "-c", help="Path to config file")


def _version_callback(value: bool) -> None:
    if value:
        print(f"ctxkit {_VERSION}")
        raise typer.Exit()


@app.callback()
def _main(
    version: bool = typer.Option(
        False, "--version", "-V",
        callback=_version_callback, is_eager=True,
        help="Show version and exit.",
    ),
) -> None:
    pass


def _load(config: Optional[str]) -> CtxKitConfig:
    cfg = load_config(config)
    from ctxkit.utils.logging import setup_logging
    setup_logging(cfg.logging)
    return cfg


def _make_store(cfg: CtxKitConfig):
    from ctxkit.store.vector_store import VectorStore
    return VectorStore(cfg.vector_store)


def _make_engine(cfg: CtxKitConfig):
    from ctxkit.core.indexer.embedding_engine import EmbeddingEngine
    return EmbeddingEngine(cfg.embeddings)


# ── ctxkit init ──────────────────────────────────────────────────────────────

@app.command()
def init(
    config: Optional[str] = _cfg_option,
):
    """Interactive setup wizard — create ~/.ctxkit/config.yaml."""
    config_path = Path(config).expanduser() if config else DEFAULT_CONFIG_PATH

    console.print(Panel.fit(
        "[bold cyan]ctxkit init[/bold cyan] — setup wizard\n"
        "[dim]Press Enter to accept a suggestion. Ctrl+C to abort.[/dim]",
        border_style="cyan",
    ))

    # ── existing config ───────────────────────────────────────────────────────
    if config_path.exists():
        overwrite = typer.confirm(f"\nConfig already exists at {config_path}. Overwrite?", default=False)
        if not overwrite:
            console.print("[yellow]Aborted — existing config kept.[/yellow]")
            raise typer.Exit()

    # ── detect hardware + Ollama ──────────────────────────────────────────────
    ram_gb = _detect_ram_gb()
    hw = _hardware_label()

    console.print("\n[dim]Detecting Ollama…[/dim]", end=" ")
    pulled_models = _detect_ollama_models()
    ollama_available = bool(pulled_models)
    if ollama_available:
        console.print(f"[green]found[/green]  ({len(pulled_models)} models pulled)")
        console.print(f"  [dim]{', '.join(pulled_models[:6])}{'…' if len(pulled_models) > 6 else ''}[/dim]")
    else:
        console.print("[yellow]not found[/yellow]  (Ollama not running or not installed)")

    console.print(f"[dim]Hardware: {hw}[/dim]\n")

    # ── vault path ────────────────────────────────────────────────────────────
    console.rule("[bold]Vault", align="left")
    console.print("[dim]Absolute path to your markdown folder (Obsidian vault or any folder of .md files)[/dim]")
    default_vault = str(Path("~/Documents").expanduser())
    vault_path = typer.prompt("Vault path", default=default_vault)
    vault_path = str(Path(vault_path).expanduser())
    if not Path(vault_path).exists():
        console.print(f"[yellow]Warning:[/yellow] {vault_path} does not exist. Create it before running ctxkit index.")

    console.print("\n[dim]Owner name: your first name if the vault has subfolders for other people (e.g. a partner's notes).[/dim]")
    console.print("[dim]Queries like 'piyush career' will route to your files, not theirs. Leave blank for single-person vaults.[/dim]")
    owner_name = typer.prompt("Owner name", default="")

    # ── LLM backend ───────────────────────────────────────────────────────────
    console.rule("[bold]LLM backend", align="left")
    backend_options = {
        "1": ("ollama",    "local — no API cost, requires Ollama running"),
        "2": ("openai",    "OpenAI API (gpt-4o-mini recommended)"),
        "3": ("anthropic", "Anthropic API (claude-haiku-4-5 recommended)"),
        "4": ("gemini",    "Google Gemini API"),
    }
    for k, (name, desc) in backend_options.items():
        tag = " [green][suggested][/green]" if (k == "1" and ollama_available) or (k == "2" and not ollama_available) else ""
        console.print(f"  [{k}] {name} — {desc}{tag}")

    default_backend_key = "1" if ollama_available else "2"
    backend_key = typer.prompt("Backend", default=default_backend_key)
    backend = backend_options.get(backend_key, backend_options[default_backend_key])[0]

    api_key = ""
    if backend != "ollama":
        api_key = typer.prompt(f"{backend} API key", default="", hide_input=True)

    # ── models ────────────────────────────────────────────────────────────────
    console.rule("[bold]Models", align="left")

    synth_backend = backend   # default: synthesis uses same backend as primary

    if backend == "ollama":
        suggested_primary = _suggest_primary_model(pulled_models, ram_gb)
        suggested_synth   = _suggest_synth_model(pulled_models)
        suggested_embed   = _suggest_embed_model(pulled_models, ram_gb)

        console.print("[dim]Primary model: classification + proposals during ingest. Must be instruction-following.[/dim]")
        if pulled_models:
            console.print(f"  [dim]Pulled: {', '.join(pulled_models[:8])}[/dim]")
        console.print(f"  [dim]Suggested for {hw}: {suggested_primary}[/dim]")
        primary_model = typer.prompt("Primary model", default=suggested_primary)

        console.print(f"\n[dim]Synthesis model: rewrites raw excerpts into a briefing during ctxkit search.[/dim]")
        console.print(f"  [dim]Can be a different backend (e.g. OpenAI) — set synthesise_backend in config.[/dim]")
        console.print(f"  [dim]For Ollama: phi4-mini is ideal (non-thinking, fast, ~2.5GB). Suggested: {suggested_synth}[/dim]")
        if not any(p.startswith("phi4-mini") for p in pulled_models):
            console.print(f"  [yellow]phi4-mini not pulled — run: ollama pull phi4-mini[/yellow]")
        synth_model = typer.prompt("Synthesis model", default=suggested_synth)

        console.print(f"\n[dim]Embedding model: generates vectors for indexing and search queries.[/dim]")
        console.print(f"  [dim]Suggested for {hw}: {suggested_embed}[/dim]")
        if not any(p.startswith(suggested_embed.split(":")[0]) for p in pulled_models):
            console.print(f"  [yellow]{suggested_embed} not pulled — run: ollama pull {suggested_embed}[/yellow]")
        embed_backend = "ollama"
        embed_model = typer.prompt("Embedding model", default=suggested_embed)

    else:
        api_defaults = {
            "openai":    ("gpt-4o-mini",       "text-embedding-3-small"),
            "anthropic": ("claude-haiku-4-5",   "text-embedding-3-small"),
            "gemini":    ("gemini-2.0-flash",   "models/text-embedding-004"),
        }
        def_primary, def_embed = api_defaults.get(backend, ("gpt-4o-mini", "text-embedding-3-small"))
        primary_model = typer.prompt("Primary model", default=def_primary)
        synth_model   = ""
        console.print("\n[dim]Embedding backend (can differ from LLM backend)[/dim]")
        console.print("  [dim]Options: ollama, openai, huggingface, gemini[/dim]")
        embed_backend = typer.prompt("Embedding backend", default=backend)
        embed_model   = typer.prompt("Embedding model", default=def_embed)

    # ── write ─────────────────────────────────────────────────────────────────
    _write_init_config(
        vault_path=vault_path,
        owner_name=owner_name,
        backend=backend,
        primary_model=primary_model,
        synth_model=synth_model,
        embed_backend=embed_backend,
        embed_model=embed_model,
        api_key=api_key,
        out_path=config_path,
    )

    console.print(f"\n[green]✓[/green] Config written → [cyan]{config_path}[/cyan]")

    # ── offer to install missing deps ─────────────────────────────────────────
    try:
        cfg_written = _load(str(config_path))
        from ctxkit.core.deps import required_backends, install_packages
        statuses = required_backends(cfg_written)
        missing_deps = [s for s in statuses if not s.installed and s.packages]
        if missing_deps:
            all_pkgs: list[str] = []
            console.print("\n[yellow]Missing backend packages:[/yellow]")
            for s in missing_deps:
                console.print(f"  {s.role}/{s.backend}: {', '.join(s.packages)}")
                all_pkgs.extend(s.packages)
            seen_pkgs: set[str] = set()
            deduped_pkgs = [p for p in all_pkgs if not (p in seen_pkgs or seen_pkgs.add(p))]  # type: ignore[func-returns-value]
            if typer.confirm("\nInstall them now?", default=True):
                with Progress(SpinnerColumn(), TextColumn("{task.description}"), console=console, transient=True) as p:
                    p.add_task("Installing packages…")
                    ok = install_packages(deduped_pkgs, quiet=True)
                if ok:
                    console.print("[green]✓ Packages installed.[/green]")
                else:
                    console.print("[yellow]Install failed. Run: ctxkit deps install[/yellow]")
    except Exception:
        pass  # dep check is best-effort — don't crash init

    # ── next steps ────────────────────────────────────────────────────────────
    console.print("\n[bold]Next steps:[/bold]")
    if backend == "ollama":
        missing_models = [
            m for m in {primary_model, synth_model, embed_model}
            if m and not any(p.startswith(m.split(":")[0]) for p in pulled_models)
        ]
        if missing_models:
            console.print("  [yellow]Pull missing Ollama models:[/yellow]")
            for m in missing_models:
                console.print(f"    ollama pull {m}")
    console.print("  [cyan]ctxkit deps status[/cyan]        — verify all backend deps installed")
    console.print("  [cyan]ctxkit docs config[/cyan]        — full config guide (all fields + tuning)")
    console.print("  [cyan]ctxkit config --validate[/cyan]  — verify config is valid")
    console.print("  [cyan]ctxkit index[/cyan]              — index your vault")


# ── ctxkit index ─────────────────────────────────────────────────────────────

@app.command()
def index(
    config: Optional[str] = _cfg_option,
    verbose: bool = typer.Option(False, "--verbose", "-v"),
    inspect: Optional[str] = typer.Option(None, "--inspect", help="Show chunk breakdown for a file"),
):
    """Scan vault, show diff, confirm, index delta."""
    cfg = _load(config)

    from ctxkit.core.indexer.vault_scanner import VaultScanner
    from ctxkit.core.indexer.manifest_manager import ManifestManager
    from ctxkit.core.indexer.document_loader import DocumentLoader
    from ctxkit.core.indexer.text_splitter import TextSplitter
    from ctxkit.core.indexer.index_writer import IndexWriter

    scanner = VaultScanner(cfg.vault, cfg.indexer)
    manifest = ManifestManager(cfg.manifest, cfg.vault)
    loader = DocumentLoader(cfg.vault)
    splitter = TextSplitter(cfg.indexer)
    store = _make_store(cfg)
    engine = _make_engine(cfg)
    writer = IndexWriter(store, engine, cfg.indexer)

    with Progress(SpinnerColumn(), TextColumn("{task.description}"), console=console) as p:
        task = p.add_task("Scanning vault...")
        eligible = scanner.scan()
        p.update(task, description=f"Found {len(eligible)} eligible files")

    diff = manifest.diff(eligible)

    if inspect:
        _show_inspect(inspect, loader, splitter, cfg.vault)
        return

    if diff.total_changes == 0:
        console.print("[green]Index is up to date — nothing to do.[/green]")
        return

    # Show diff
    table = Table(title="Index Delta", box=box.ROUNDED)
    table.add_column("Status", style="cyan")
    table.add_column("File")
    for p in diff.new_files:
        table.add_row("[+] New", str(p.relative_to(Path(cfg.vault.path).expanduser())))
    for p in diff.modified_files:
        table.add_row("[~] Modified", str(p.relative_to(Path(cfg.vault.path).expanduser())))
    for k in diff.deleted_files:
        table.add_row("[-] Deleted", k)
    console.print(table)

    if cfg.cli.confirm_before_index:
        choice = typer.prompt("[A]ll / [C]ancel", default="A").strip().upper()
        if choice != "A":
            console.print("Cancelled.")
            return

    files_to_index = diff.new_files + diff.modified_files
    start = datetime.now(timezone.utc)
    skipped: list[tuple[Path, str]] = []

    from ctxkit.utils.logging import get_logger
    _log = get_logger("cli.index")

    with Progress(SpinnerColumn(), BarColumn(), TextColumn("{task.description}"), console=console) as p:
        task = p.add_task("Indexing...", total=len(files_to_index))
        for path in files_to_index:
            try:
                doc = loader.load(path)
                chunks = splitter.split(doc)
                source_file = doc.metadata.get("source_file", str(path))
                writer.write(chunks, source_file)
                manifest.update(path)
                if verbose:
                    console.print(f"  [dim]Indexed {source_file} → {len(chunks)} chunks[/dim]")
            except Exception as exc:
                _log.exception("Failed to index %s", path)
                skipped.append((path, str(exc)))
                console.print(f"  [yellow]⚠ Skipped:[/yellow] {path.name} — {exc}")
            finally:
                p.advance(task)

    for key in diff.deleted_files:
        store.delete(key)
        manifest.remove(key)

    elapsed = (datetime.now(timezone.utc) - start).total_seconds()
    indexed_count = len(files_to_index) - len(skipped)
    summary = (
        f"[green]Done.[/green] {indexed_count} indexed, "
        f"{len(diff.deleted_files)} removed in {elapsed:.1f}s"
    )
    if skipped:
        summary += f" [yellow]· {len(skipped)} skipped (see warnings above)[/yellow]"
    console.print(summary)


def _show_inspect(filename: str, loader, splitter, vault_cfg):
    from pathlib import Path
    vault = Path(vault_cfg.path).expanduser()
    matches = list(vault.rglob(f"*{filename}*"))
    if not matches:
        console.print(f"[red]No file matching '{filename}' found.[/red]")
        return
    path = matches[0]
    doc = loader.load(path)
    chunks = splitter.split(doc)
    table = Table(title=f"Chunks: {path.name}", box=box.SIMPLE)
    table.add_column("#", style="dim")
    table.add_column("Breadcrumb")
    table.add_column("Words")
    table.add_column("Table")
    table.add_column("Code")
    for c in chunks:
        m = c.metadata
        table.add_row(
            str(m.get("chunk_index", "?")),
            m.get("heading_breadcrumb", "—"),
            str(m.get("word_count", "?")),
            "✓" if m.get("is_table") else "",
            "✓" if m.get("is_code") else "",
        )
    console.print(table)


# ── ctxkit search ────────────────────────────────────────────────────────────

def _query_slug(topic: str) -> str:
    """Convert query to a safe filename slug: lowercase, hyphens, max 60 chars."""
    import re
    slug = re.sub(r"[^\w\s-]", "", topic.lower())
    slug = re.sub(r"[\s_]+", "-", slug).strip("-")
    return slug[:60]


@app.command()
def search(
    topic: str = typer.Argument(..., help="Topic to search for"),
    config: Optional[str] = _cfg_option,
    verbose: bool = typer.Option(False, "--verbose", "-v"),
    raw: bool = typer.Option(
        False, "--raw", "-r",
        help="Write raw retrieved excerpts instead of synthesised briefing.",
    ),
):
    """Flow A — retrieve context, synthesise with local LLM, write to MD file."""
    cfg = _load(config)

    from ctxkit.core.retriever.keyword_prefilter import KeywordPreFilter
    from ctxkit.core.retriever.vector_searcher import VectorSearcher
    from ctxkit.core.retriever.chunk_grouper import group_by_source
    from ctxkit.core.retriever.chunk_stitcher import stitch
    from ctxkit.core.retriever.source_ranker import rank_sources
    from ctxkit.core.retriever.context_assembler import assemble
    from ctxkit.core.retriever.context_formatter import format_context, raw_text_for_synthesis

    store = _make_store(cfg)
    engine = _make_engine(cfg)

    with Progress(SpinnerColumn(), TextColumn("{task.description}"), console=console, transient=True) as p:
        p.add_task("Searching...")

        all_metadata = store.all_metadata()
        if not all_metadata:
            console.print("[yellow]Index is empty. Run [bold]ctxkit index[/bold] first.[/yellow]")
            return

        candidate_sources: set[str] | None = None
        if cfg.retriever.keyword_prefilter:
            prefilter = KeywordPreFilter(
                cfg.retriever.keyword_prefilter_min_score,
                owner_name=cfg.vault.owner_name,
            )
            candidate_sources = prefilter.filter(topic, all_metadata) or None

        # Strip owner name from vector query — not in content, adds noise.
        vector_query = topic
        if cfg.vault.owner_name:
            owner_words_lc = {w.lower() for w in cfg.vault.owner_name.split()}
            stripped = " ".join(w for w in topic.split() if w.lower() not in owner_words_lc)
            if stripped.strip():
                vector_query = stripped.strip()

        searcher = VectorSearcher(store, engine, cfg.retriever)
        chunks = searcher.search(vector_query, candidate_sources)

    if not chunks:
        console.print(f"[yellow]No results found for '{topic}'. Try lowering similarity_threshold in config.[/yellow]")
        return

    if verbose:
        console.print(f"[dim]Raw chunks: {len(chunks)}[/dim]")

    groups = group_by_source(chunks)
    passages_by_source = {sf: stitch(sf, c, cfg.retriever) for sf, c in groups.items()}
    ranked = rank_sources(passages_by_source)
    ctx = assemble(topic, ranked, cfg.retriever)

    # ── Build output content ──────────────────────────────────────────────────
    now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    source_lines = "\n".join(
        f"- [{i}] {sf}" for i, (sf, _) in enumerate(ctx.primary, 1)
    )

    if raw:
        raw_output = format_context(ctx, cfg.retriever)
        md_content = (
            f"# {topic}\n\n"
            f"*{now_str} · {ctx.source_count} sources · raw excerpts*\n\n"
            f"## Sources\n\n{source_lines}\n\n"
            "---\n\n"
            f"{raw_output}"
        )
        mode_label = "raw"
    else:
        from ctxkit.llm.llm_layer import LLMLayer
        llm = LLMLayer(cfg.llm)
        raw_text = raw_text_for_synthesis(ctx)
        synth_model_name = cfg.llm.synthesise_model or cfg.llm.model

        with Progress(SpinnerColumn(), TextColumn("{task.description}"), console=console, transient=True) as p:
            p.add_task(f"Synthesising with {synth_model_name}…")
            briefing = llm.synthesise(topic, raw_text)

        raw_output = format_context(ctx, cfg.retriever)
        md_content = (
            f"# {topic}\n\n"
            f"*{now_str} · {ctx.source_count} sources · synthesised by {synth_model_name}*\n\n"
            f"> ⚠ Verify claims against raw excerpts below.\n\n"
            f"## Sources\n\n{source_lines}\n\n"
            "---\n\n"
            f"## Briefing\n\n{briefing}\n\n"
            "---\n\n"
            f"## Raw Excerpts\n\n{raw_output}"
        )
        mode_label = f"synthesised · {synth_model_name}"

    # ── Write to output folder ────────────────────────────────────────────────
    # Output lives at <vault>/ctxkit-output/ — fixed location, always excluded from indexing.
    out_dir = Path(cfg.vault.path).expanduser() / "ctxkit-output"
    out_dir.mkdir(parents=True, exist_ok=True)
    date_prefix = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    filename = f"{date_prefix}-{_query_slug(topic)}.md"
    out_path = out_dir / filename

    out_path.write_text(md_content, encoding="utf-8")
    console.print(f"[green]✓[/green] Saved → [cyan]{out_path}[/cyan]  [dim]({ctx.source_count} sources · {mode_label})[/dim]")


# ── ctxkit ingest ─────────────────────────────────────────────────────────────

@app.command()
def ingest(
    file: Optional[str] = typer.Option(None, "--file", "-f", help="Path to summary file"),
    config: Optional[str] = _cfg_option,
):
    """Flow B — accept session summary, classify, propose."""
    cfg = _load(config)

    from ctxkit.core.ingester.summary_receiver import SummaryReceiver
    from ctxkit.core.ingester.summary_embedder import SummaryEmbedder
    from ctxkit.core.ingester.classification_engine import ClassificationEngine
    from ctxkit.core.ingester.folder_router import FolderRouter
    from ctxkit.core.ingester.conflict_detector import ConflictDetector
    from ctxkit.core.ingester.proposal_generator import ProposalGenerator
    from ctxkit.llm.llm_layer import LLMLayer

    receiver = SummaryReceiver(cfg.ingester)
    store = _make_store(cfg)
    engine = _make_engine(cfg)
    llm = LLMLayer(cfg.llm)

    try:
        if file:
            summary = receiver.receive_from_file(file)
        else:
            console.print("[bold]Paste your session summary below. Press [Ctrl+D] when done:[/bold]")
            lines = sys.stdin.read()
            summary = receiver.receive_from_text(lines)
    except (ValueError, FileNotFoundError) as exc:
        err_console.print(f"Input error: {exc}")
        raise typer.Exit(1)

    with Progress(SpinnerColumn(), TextColumn("{task.description}"), console=console, transient=True) as p:
        p.add_task("Classifying...")
        from ctxkit.core.ingester.summary_embedder import SummaryEmbedder
        embedder = SummaryEmbedder(engine)
        embs = embedder.embed(summary)
        classify_engine = ClassificationEngine(store, llm, cfg.ingester)
        decision = classify_engine.classify(embs.full, summary)

    console.print(f"\nAction: [bold]{decision.action.upper()}[/bold]")
    if decision.target_file:
        console.print(f"Target: [cyan]{decision.target_file}[/cyan]")
    console.print(f"Confidence: {decision.confidence:.2f}")
    console.print(f"Reasoning: [dim]{decision.reasoning}[/dim]")
    if decision.used_llm:
        console.print("[dim](LLM was consulted for ambiguous classification)[/dim]")

    existing_content = ""
    conflicts = []
    if decision.action == "update" and decision.target_file:
        vault_path = Path(cfg.vault.path).expanduser()
        existing_path = vault_path / decision.target_file
        if existing_path.exists():
            existing_content = existing_path.read_text(encoding="utf-8", errors="ignore")
            detector = ConflictDetector(engine, cfg.ingester)
            conflicts = detector.detect(existing_content, summary)

    folder = ""
    if decision.action == "new":
        router = FolderRouter(cfg.vault, cfg.ingester)
        folder, folder_confidence = router.route(summary)
        if router.needs_confirmation(folder_confidence):
            console.print(f"\n[yellow]Suggested folder: '{folder}' (low confidence)[/yellow]")
            override = typer.prompt("Enter folder path or press Enter to accept", default=folder)
            folder = override.strip()
        else:
            console.print(f"Suggested folder: [cyan]{folder}[/cyan]")

    from datetime import date
    fm_updates = {"updated": str(date.today()), "tags": [], "related": []}

    with Progress(SpinnerColumn(), TextColumn("{task.description}"), console=console, transient=True) as p:
        p.add_task("Generating proposal...")
        generator = ProposalGenerator(llm)
        proposal = generator.generate(decision, summary, existing_content, conflicts, folder, fm_updates)

    _render_proposal(proposal)

    choice = typer.prompt("\n[A]pprove / [E]dit first / [R]eject", default="R").strip().upper()
    if choice == "R":
        console.print("[dim]Rejected. No changes made.[/dim]")
        return
    if choice == "E":
        console.print("[yellow]Edit mode: open your editor, save the summary, then re-run ctxkit ingest --file <path>[/yellow]")
        return

    _execute_write(cfg, proposal, summary, existing_content)


def _render_proposal(proposal):
    from ctxkit.core.ingester.proposal_generator import Proposal
    lines = [
        "PROPOSAL — ctxkit ingestion",
        "─" * 45,
        f"Action:     {proposal.action.upper()} {'existing file' if proposal.action == 'update' else 'new file'}",
    ]
    if proposal.target_file:
        lines.append(f"Target:     {proposal.target_file}")
    elif proposal.suggested_folder:
        lines.append(f"Folder:     {proposal.suggested_folder}")
    lines.append(f"Confidence: {proposal.confidence:.2f}")
    lines.append("")
    lines.append("Changes proposed:")
    for line in proposal.proposal_text.strip().splitlines():
        lines.append(f"  {line}")
    if proposal.conflicts:
        lines.append("")
        lines.append("Possible conflicts detected:")
        for c in proposal.conflicts[:3]:
            lines.append(f"  ! Existing:  \"{c.existing_sentence[:80]}\"")
            lines.append(f"    Incoming:  \"{c.incoming_sentence[:80]}\"")
            lines.append(f"    → Review before approving (similarity {c.similarity:.2f})")
    lines.append("─" * 45)
    console.print(Panel("\n".join(lines), title="[bold]ctxkit proposal[/bold]", expand=False))


def _execute_write(cfg: CtxKitConfig, proposal, summary: str, existing_content: str):
    from ctxkit.core.writer.backup_manager import BackupManager
    from ctxkit.core.writer.frontmatter_injector import FrontmatterInjector
    from ctxkit.core.writer.file_writer import FileWriter
    from ctxkit.core.writer.index_trigger import IndexTrigger
    from ctxkit.core.indexer.manifest_manager import ManifestManager
    from ctxkit.core.indexer.document_loader import DocumentLoader
    from ctxkit.core.indexer.text_splitter import TextSplitter
    from ctxkit.core.indexer.index_writer import IndexWriter

    vault_path = Path(cfg.vault.path).expanduser()
    backup_mgr = BackupManager(cfg.writer.backup)
    fm_injector = FrontmatterInjector(cfg.writer.frontmatter)
    file_writer = FileWriter(cfg.vault, cfg.writer)
    store = _make_store(cfg)
    engine = _make_engine(cfg)

    def _factory():
        loader = DocumentLoader(cfg.vault)
        splitter = TextSplitter(cfg.indexer)
        idx_writer = IndexWriter(store, engine, cfg.indexer)
        manifest = ManifestManager(cfg.manifest, cfg.vault)
        return loader, splitter, idx_writer, manifest

    trigger = IndexTrigger(_factory)

    if proposal.action == "update" and proposal.target_file:
        target = vault_path / proposal.target_file
        backup_mgr.backup(target)
        updated_fm = fm_injector.inject(target, proposal.frontmatter_updates)
        file_writer.update(target, updated_fm, summary)
        trigger.reindex(target)
        console.print(f"[green]Updated:[/green] {proposal.target_file}")
    else:
        filename = _derive_filename(summary)
        new_path = file_writer.create(proposal.suggested_folder, filename, summary)
        trigger.reindex(new_path)
        console.print(f"[green]Created:[/green] {new_path}")


def _derive_filename(summary: str) -> str:
    import re
    for line in summary.splitlines():
        m = re.match(r"^#{1,3}\s+(.+)$", line)
        if m:
            title = m.group(1).strip()
            safe = re.sub(r"[^a-z0-9\- ]", "", title.lower())
            return safe.replace(" ", "-")[:50] + ".md"
    return "ingested-note.md"


# ── ctxkit status ─────────────────────────────────────────────────────────────

@app.command()
def status(config: Optional[str] = _cfg_option):
    """Show index health, drift warnings, last sync."""
    cfg = _load(config)

    from ctxkit.core.indexer.vault_scanner import VaultScanner
    from ctxkit.core.indexer.manifest_manager import ManifestManager

    scanner = VaultScanner(cfg.vault, cfg.indexer)
    manifest = ManifestManager(cfg.manifest, cfg.vault)
    store = _make_store(cfg)

    eligible = scanner.scan()
    diff = manifest.diff(eligible)
    all_meta = store.all_metadata()
    indexed_files = len({m.get("source_file") for m in all_meta})
    total_chunks = len(all_meta)

    table = Table(title="ctxkit status", box=box.ROUNDED)
    table.add_column("Item", style="cyan")
    table.add_column("Value")
    table.add_row("Vault path", cfg.vault.path)
    table.add_row("Eligible files", str(len(eligible)))
    table.add_row("Indexed files", str(indexed_files))
    table.add_row("Total chunks", str(total_chunks))
    table.add_row("New (unindexed)", str(len(diff.new_files)))
    table.add_row("Modified (stale)", str(len(diff.modified_files)))
    table.add_row("Deleted", str(len(diff.deleted_files)))
    console.print(table)

    if diff.total_changes >= cfg.manifest.drift_warning_threshold:
        console.print(
            f"[yellow]⚠ Index drift detected: {diff.total_changes} file(s) out of sync. "
            f"Run [bold]ctxkit index[/bold] to update.[/yellow]"
        )
    else:
        console.print("[green]Index is healthy.[/green]")


# ── ctxkit eval ───────────────────────────────────────────────────────────────

@app.command()
def eval(
    topic: Optional[str] = typer.Argument(None, help="Topic to evaluate (runs a search if provided)"),
    config: Optional[str] = _cfg_option,
):
    """Run user-guided quality check on retrieval output."""
    cfg = _load(config)

    if topic:
        console.print(f"[bold]Running search for evaluation: '{topic}'[/bold]\n")
        # Invoke search inline
        from ctxkit.core.retriever.keyword_prefilter import KeywordPreFilter
        from ctxkit.core.retriever.vector_searcher import VectorSearcher
        from ctxkit.core.retriever.chunk_grouper import group_by_source
        from ctxkit.core.retriever.chunk_stitcher import stitch
        from ctxkit.core.retriever.source_ranker import rank_sources
        from ctxkit.core.retriever.context_assembler import assemble
        from ctxkit.core.retriever.context_formatter import format_context

        store = _make_store(cfg)
        engine = _make_engine(cfg)
        all_metadata = store.all_metadata()

        candidate_sources = None
        if cfg.retriever.keyword_prefilter:
            prefilter = KeywordPreFilter(
                cfg.retriever.keyword_prefilter_min_score,
                owner_name=cfg.vault.owner_name,
            )
            candidate_sources = prefilter.filter(topic, all_metadata) or None

        searcher = VectorSearcher(store, engine, cfg.retriever)
        chunks = searcher.search(topic, candidate_sources)
        if not chunks:
            console.print("[yellow]No results found.[/yellow]")
            return

        groups = group_by_source(chunks)
        passages_by_source = {sf: stitch(sf, c, cfg.retriever) for sf, c in groups.items()}
        ranked = rank_sources(passages_by_source)
        ctx = assemble(topic, ranked, cfg.retriever)
        output = format_context(ctx, cfg.retriever)
        console.print(Markdown(output))
        console.rule()

    console.print(Panel(
        "[bold]Evaluation checklist[/bold]\n\n"
        "1. Is word count close to target (1000 words)?\n"
        "2. Are the right sources cited?\n"
        "3. Is content within each passage coherent?\n"
        "4. Would this context block give a subscription LLM enough to work with?\n\n"
        "See [bold]ctxkit-retrieval-and-eval-guide.md[/bold] for the symptom-to-fix guide.",
        title="[cyan]ctxkit eval[/cyan]",
        expand=False,
    ))


# ── ctxkit deps ───────────────────────────────────────────────────────────────

@app.command()
def deps(
    action: str = typer.Argument("status", help="Action: status | install"),
    config: Optional[str] = _cfg_option,
):
    """Show or install backend dependencies based on current config.

    \b
    ctxkit deps status   — show what config needs vs what is installed
    ctxkit deps install  — install any missing packages
    """
    from ctxkit.core.deps import required_backends, install_packages

    cfg = _load(config)
    statuses = required_backends(cfg)

    if action == "status":
        t = Table(title="Dependency status", box=box.SIMPLE, show_header=True)
        t.add_column("Role", style="dim")
        t.add_column("Backend")
        t.add_column("Status")
        t.add_column("Packages needed")
        for s in statuses:
            status_str = "[green]✓ installed[/green]" if s.installed else "[red]✗ missing[/red]"
            pkgs = ", ".join(s.packages) if s.packages else "[dim]in core[/dim]"
            t.add_row(s.role, s.backend, status_str, pkgs)
        console.print(t)

        missing = [s for s in statuses if not s.installed]
        if missing:
            console.print(f"\n[yellow]{len(missing)} backend(s) have missing deps.[/yellow]  Run: [cyan]ctxkit deps install[/cyan]")
        else:
            console.print("\n[green]All backends installed.[/green]")

    elif action == "install":
        missing = [s for s in statuses if not s.installed and s.packages]
        if not missing:
            console.print("[green]Nothing to install — all backends already available.[/green]")
            return

        all_pkgs: list[str] = []
        for s in missing:
            console.print(f"  [dim]{s.role}/{s.backend}:[/dim] {', '.join(s.packages)}")
            all_pkgs.extend(s.packages)

        # deduplicate preserving order
        seen: set[str] = set()
        deduped = [p for p in all_pkgs if not (p in seen or seen.add(p))]  # type: ignore[func-returns-value]

        console.print(f"\nInstalling {len(deduped)} package(s) into [dim]{sys.executable}[/dim]…")
        with Progress(SpinnerColumn(), TextColumn("{task.description}"), console=console, transient=True) as p:
            p.add_task("Running pip install…")
            ok = install_packages(deduped, quiet=True)

        if ok:
            console.print("[green]✓ Done.[/green]  Run [cyan]ctxkit deps status[/cyan] to verify.")
        else:
            err_console.print("pip install failed. Check output above.")
            raise typer.Exit(1)

    else:
        err_console.print(f"Unknown action '{action}'. Use: status | install")
        raise typer.Exit(1)


# ── ctxkit docs / config ──────────────────────────────────────────────────────

@app.command()
def docs(
    topic: str = typer.Argument(
        "config",
        help="Topic to read: config, getting-started, retrieval",
    ),
):
    """Show documentation in the terminal.

    Topics: config, getting-started (start), retrieval (eval)
    """
    from importlib.resources import files

    topic_map: dict[str, str] = {
        "config":          "config-reference.md",
        "conf":            "config-reference.md",
        "getting-started": "getting-started.md",
        "start":           "getting-started.md",
        "setup":           "getting-started.md",
        "retrieval":       "retrieval-and-eval-guide.md",
        "eval":            "retrieval-and-eval-guide.md",
        "tuning":          "retrieval-and-eval-guide.md",
    }
    filename = topic_map.get(topic.lower())
    if not filename:
        available = ", ".join(sorted({k for k in topic_map if k == topic_map[k].replace("-", " ").split(".")[0] or True}))
        err_console.print(f"Unknown topic '{topic}'. Available: {', '.join(sorted(set(topic_map.keys())))}")
        raise typer.Exit(1)

    try:
        content = files("ctxkit.docs").joinpath(filename).read_text(encoding="utf-8")
    except Exception as exc:
        err_console.print(f"Could not load docs/{filename}: {exc}")
        raise typer.Exit(1)

    console.print(Markdown(content))


@app.command(name="config")
def config_cmd(
    validate: bool = typer.Option(False, "--validate", help="Validate config file and report errors"),
    config: Optional[str] = _cfg_option,
):
    """Open config file in default editor, or validate it."""
    config_path = Path(config).expanduser() if config else DEFAULT_CONFIG_PATH
    if validate:
        try:
            cfg = load_config(config)
            console.print(f"[green]Config valid:[/green] {config_path}")
        except SystemExit as exc:
            console.print(str(exc))
        return
    # Open in default editor
    if not config_path.exists():
        config_path.parent.mkdir(parents=True, exist_ok=True)
        import shutil as _shutil
        example = Path(__file__).parent.parent.parent / "config.yaml.example"
        if example.exists():
            _shutil.copy(example, config_path)
            console.print(f"[dim]Copied example config to {config_path}[/dim]")
    import os
    editor = os.environ.get("EDITOR", "vi")
    subprocess.run([editor, str(config_path)])
