class Ctxkit < Formula
  include Language::Python::Virtualenv

  desc "Context portability and knowledge ingestion tool — bridge your markdown vault to any subscription LLM"
  homepage "https://github.com/YOUR_USERNAME/context-portability-tool"
  url "https://files.pythonhosted.org/packages/.../ctxkit-1.2.0.tar.gz"
  sha256 "REPLACE_WITH_ACTUAL_SHA256_AFTER_PYPI_PUBLISH"
  license "MIT"

  depends_on "python@3.12"

  # Core deps only. Backend extras installed via: ctxkit deps install
  resource "typer" do
    url "https://files.pythonhosted.org/packages/.../typer-0.12.0.tar.gz"
    sha256 "..."
  end

  # NOTE: Full resource list is auto-generated by:
  #   brew update-python-resources ctxkit.rb
  # Run this after updating the formula to regenerate all resource blocks.

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match "ctxkit", shell_output("#{bin}/ctxkit --help")
  end
end
